# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.2
    hooks:
      - id: prettier
        args: [--write, --no-semi, --print-width=88, --arrow-parens=avoid]
        additional_dependencies:
          - prettier@2.5.1
          - prettier-plugin-svelte@v2.6.0
          - svelte@v3.46.2
