services:
  api:
    build: ./api
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - 2000:2000
    links:
      - mongo
    volumes:
      - ./api:/app
    networks:
      - extern
      - intern
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-web.rule=Host(`python.${HOST_NAME}`)"
      - "traefik.http.routers.backend-secured.rule=Host(`python.${HOST_NAME}`)"
      - "traefik.http.routers.backend-secured.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=traefik"
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
    networks:
      - intern
      - extern
  mongo:
    image: mongo:5.0.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - intern
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - intern
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  traefik:
    image: traefik:v2.5
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=false
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=ERROR
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=theafkdeveloper@gmail.com
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - extern
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`monitor.${HOST_NAME}`)"
      - "traefik.http.routers.api.service=api@internal"

networks:
  extern:
    external: true
  intern:
    external: false
