services:
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 2000:2000
    links:
      - mongo
    volumes:
      - ./api:/app
  rust_api:
    build:
      context: ./rust_api
      target: ${APP_ENVIRONMENT}
      args:
        - APP_ENV=${APP_ENVIRONMENT}
    container_name: rust_api
    restart: always
    ports:
      - 9000:9000
    links:
      - mongo
    volumes:
      - ./rust_api:/app
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
  mongo:
    image: mongo:5.0.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
