[package]
name = "rust_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tide = "0.15.0"
mongodb = "2.1.0"
tokio = "1"
serde = { version = "1.0.136", features = ["derive"] }
