name: Rust formatting and linting

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run rustfmt
        run: |
          cargo fmt --manifest-path rust_api/Cargo.toml
      - name: Run clippy
        run: |
          cargo clippy --manifest-path rust_api/Cargo.toml -- -W clippy::correctness -D warnings
